version: '3.9'

services:
  app:
    build:
      context: .
      # defaults to current dictory so will pickup Dockerfile on this level
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    # overrides docker command to start container
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      # for local development only
      - DEBUG=1
      - DB_HOST=db
      # name of the service we're connecting to
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
      # set up dependency on app container on the db container. db should start before app. there should be a network connection setup between app and db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

  front_end:
    build:
      context: ./front_end
    ports:
      - "3000:3000"
    container_name: front_end

    volumes:
      - ./front_end:/front_end
      - /front_end/node_modules
    