version: '3.9'

services:
  app:
    build:
      context: .
      # defaults to current dictory so will pickup Dockerfile on this level
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
    # for local development only
      - DEBUG=1

